typedef enum AMF_TYPE{
    AMF_TYPE_NUMBER,
    AMF_TYPE_BOOLEAN,
    AMF_TYPE_STRING,
    AMF_TYPE_OBJECT,
    AMF_TYPE_MOVIECLIP,
    AMF_TYPE_NULL,
    AMF_TYPE_UNDEFINED,
    AMF_TYPE_REFERENCE,
    AMF_TYPE_ECMA_ARRAY,
    AMF_TYPE_OBJECT_END,
    AMF_TYPE_STRICT_ARRAY,
    AMF_TYPE_DATE,
    AMF_TYPE_LONG_STRING,
    AMF_TYPE_UNSUPPORTED,
    AMF_TYPE_RECORDSET,
    AMF_TYPE_XML_DOCUMENT,
    AMF_TYPE_TYPED_OBJECT,
    AMF_TYPE_AVMPLUS
} amf_type_t;

typedef enum AMF_ERR {
    AMF_ERR_NONE,
    AMF_ERR_INVALID_DATA = -10,
    AMF_ERR_INCOMPLETE
} amf_err_t;
